# Generated by Django 3.1.4 on 2020-12-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='plant_images')),
                ('name', models.CharField(default='None', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
