# Generated by Django 3.1.4 on 2020-12-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurseries', '0002_auto_20201218_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nurseries.plant')),
            ],
        ),
    ]
